apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    course: DevOPS
    Trainer: SivakumarReddy
spec:
  # list of containers
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  